sudo: required
dist: trusty
language: c++
before_install:
  - git clone https://github.com/benedictpaten/sonLib.git
install:
  - sh -c 'cd sonLib && make'
script:
  - export sonLibRootPath=`pwd`/sonLib
  - make && make test
os:
  - linux
  - osx
env:
  - CGL_DEBUG=1
  - CGL_DEBUG=ultra
matrix:
  exclude:
    # The default OSX env doesn't have a version that supports
    # -fsanitize=address.
    - env: CGL_DEBUG=ultra
      os: osx
